Class Demo.Vector.Document Extends Demo.Vector.Base
{

Storage Default
{
<Data name="DocumentDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
<Value name="2">
<Value>uid</Value>
</Value>
<Value name="3">
<Value>document</Value>
</Value>
<Value name="4">
<Value>embedding</Value>
</Value>
<Value name="5">
<Value>userName</Value>
</Value>
<Value name="7">
<Value>timestamp</Value>
</Value>
<Value name="8">
<Value>metadata</Value>
</Value>
</Data>
<DataLocation>^Demo.Vector.DocumentD</DataLocation>
<DefaultData>DocumentDefaultData</DefaultData>
<IdLocation>^Demo.Vector.DocumentD</IdLocation>
<IndexLocation>^Demo.Vector.DocumentI</IndexLocation>
<StreamLocation>^Demo.Vector.DocumentS</StreamLocation>
<Type>%Storage.Persistent</Type>
}

}
