    
    zn "USER"
    do $SYSTEM.OBJ.Load("/home/irisowner/dev/zpm-0.10.7.xml","ck")
    zpm "enable -map -globally"

    zn "%SYS"

    set app = "/csp/sc"
    set appProperties("DeepSeeEnabled")=1
    set sc = ##class(Security.Applications).Modify(app,.appProperties)
    
    zn "SC"

    set f = ##class(%File).%New("/home/irisowner/dev/key/zpm.json")
    do f.Open("R")
    set content=""
    while 'f.AtEnd {
        set content = content _ f.ReadLine()
    }
    set zpm = {}.%FromJSON(content)  

    zpm "repo -o -name isc -url https://ipm.intersystems.com -username "_ zpm.login_" -password "_ zpm.password
    zpm "install isc-supply-chain"

    halt